### ISSUE TITLE
Native resolution

### ISSUE THREAD

**Issue by nsajko** [AquariaOSE/Aquaria#17]
In the options the native screen resolution is offered when you're choosing game resolution.
But if the native resolution is already known, why wouldn't the game just start in it?

**Comment by fgenesis** [comment]
Because you want to set a lower res if you have an old system?
Or windowed mode with a non-standard resolution that spans multiple screens?

However i do agree that the default setting being 800x600 isn't such a good idea; will see how to make this a bit more sane. E.g. 0x0 resolution would mean to autodetect, or so...

**Comment by nsajko** [comment]
OK, then. :)

**Comment by fgenesis** [comment]
Note to self: Add "Desktop" option to resolutions menu, that uses SDL_FULLSCREEN_DESKTOP flag when in fullscreen, and desktop res otherwise.
